version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mysql://root:151515@db:3306/uniplato
      JWT_KEY: "@4b0Lf4zl"

    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 151515
      MYSQL_DATABASE: uniplato
    ports:
      - "3316:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  app-network:
    driver: bridge
